const sentenceData = {

1: [

{en:"He writes a letter", ta:"அவன் ஒரு கடிதத்தை எழுதுகிறான்"},
{en:"She reads a novel", ta:"அவள் ஒரு நாவலைப் படிக்கிறாள்"},
{en:"They play football", ta:"அவர்கள் கால்பந்து விளையாடுகிறார்கள்"},
{en:"We watch the news", ta:"நாங்கள் செய்திகளைப் பார்க்கிறோம்"},
{en:"The teacher explains the lesson", ta:"ஆசிரியர் பாடத்தை விளக்குகிறார்"},
{en:"The student answers correctly", ta:"மாணவர் சரியாகப் பதிலளிக்கிறார்"},
{en:"The farmer grows rice", ta:"விவசாயி நெல் வளர்க்கிறார்"},
{en:"The doctor treats patients", ta:"மருத்துவர் நோயாளிகளை சிகிச்சையளிக்கிறார்"},
{en:"The boy sings a song", ta:"சிறுவன் ஒரு பாடலைப் பாடுகிறான்"},
{en:"The girl draws a picture", ta:"சிறுமி ஒரு படத்தை வரைகிறாள்"},

{en:"He drives a car", ta:"அவன் ஒரு காரை ஓட்டுகிறான்"},
{en:"She cooks dinner", ta:"அவள் இரவு உணவைச் சமைக்கிறாள்"},
{en:"They clean the classroom", ta:"அவர்கள் வகுப்பறையை சுத்தம் செய்கிறார்கள்"},
{en:"We learn English grammar", ta:"நாங்கள் ஆங்கில இலக்கணத்தை கற்கிறோம்"},
{en:"The sun rises in the east", ta:"சூரியன் கிழக்கில் உதயமாகிறது"},
{en:"The moon shines brightly", ta:"நிலா பிரகாசமாக ஒளிர்கிறது"},
{en:"Birds fly in the sky", ta:"பறவைகள் வானில் பறக்கின்றன"},
{en:"The cat drinks milk", ta:"பூனை பாலை குடிக்கிறது"},
{en:"The dog guards the house", ta:"நாய் வீட்டைக் காக்கிறது"},
{en:"Students attend classes", ta:"மாணவர்கள் வகுப்புகளில் கலந்து கொள்கிறார்கள்"},

{en:"He studies mathematics", ta:"அவன் கணிதத்தைப் படிக்கிறான்"},
{en:"She practices yoga", ta:"அவள் யோகா பயிற்சி செய்கிறாள்"},
{en:"They build houses", ta:"அவர்கள் வீடுகளை கட்டுகிறார்கள்"},
{en:"We celebrate festivals", ta:"நாங்கள் திருவிழாக்களை கொண்டாடுகிறோம்"},
{en:"The child smiles happily", ta:"குழந்தை மகிழ்ச்சியாகச் சிரிக்கிறது"},
{en:"He respects his parents", ta:"அவன் தனது பெற்றோர்களை மதிக்கிறான்"},
{en:"She helps the poor", ta:"அவள் ஏழைகளுக்கு உதவுகிறாள்"},
{en:"They plant trees", ta:"அவர்கள் மரங்களை நடுகிறார்கள்"},
{en:"We follow the rules", ta:"நாங்கள் விதிகளைப் பின்பற்றுகிறோம்"},
{en:"The engine runs smoothly", ta:"இயந்திரம் சீராக இயங்குகிறது"},

{en:"He teaches science", ta:"அவன் அறிவியலை கற்பிக்கிறான்"},
{en:"She writes essays", ta:"அவள் கட்டுரைகளை எழுதுகிறாள்"},
{en:"They solve problems", ta:"அவர்கள் பிரச்சினைகளை தீர்க்கிறார்கள்"},
{en:"We drink clean water", ta:"நாங்கள் சுத்தமான தண்ணீரைக் குடிக்கிறோம்"},
{en:"The shop opens at nine", ta:"கடை ஒன்பது மணிக்கு திறக்கப்படுகிறது"},
{en:"The river flows rapidly", ta:"நதி வேகமாக ஓடுகிறது"},
{en:"He completes his homework", ta:"அவன் தனது வீட்டுப்பாடத்தை முடிக்கிறான்"},
{en:"She attends the meeting", ta:"அவள் கூட்டத்தில் கலந்து கொள்கிறாள்"},
{en:"They organize events", ta:"அவர்கள் நிகழ்ச்சிகளை ஒழுங்குபடுத்துகிறார்கள்"},
{en:"We maintain discipline", ta:"நாங்கள் ஒழுக்கத்தைப் பேணுகிறோம்"},

{en:"The baby cries loudly", ta:"குழந்தை சத்தமாக அழுகிறது"},
{en:"He buys vegetables", ta:"அவன் காய்கறிகளை வாங்குகிறான்"},
{en:"She wears a uniform", ta:"அவள் சீருடையை அணிகிறாள்"},
{en:"They travel by bus", ta:"அவர்கள் பேருந்தில் பயணம் செய்கிறார்கள்"},
{en:"We observe silence", ta:"நாங்கள் அமைதியைப் பின்பற்றுகிறோம்"},
{en:"The bell rings loudly", ta:"மணி சத்தமாக ஒலிக்கிறது"},
{en:"He listens carefully", ta:"அவன் கவனமாகக் கேட்கிறான்"},
{en:"She decorates the hall", ta:"அவள் மண்டபத்தை அலங்கரிக்கிறாள்"},
{en:"They repair the road", ta:"அவர்கள் சாலையை பழுது பார்க்கிறார்கள்"},
{en:"We appreciate good work", ta:"நாங்கள் நல்ல பணியை பாராட்டுகிறோம்"},

{en:"The train arrives on time", ta:"ரயில் நேரத்திற்கு வருகிறது"},
{en:"He joins the team", ta:"அவன் அணியில் சேருகிறான்"},
{en:"She improves her skills", ta:"அவள் தனது திறன்களை மேம்படுத்துகிறாள்"},
{en:"They respect the law", ta:"அவர்கள் சட்டத்தை மதிக்கிறார்கள்"},
{en:"We protect the environment", ta:"நாங்கள் சுற்றுச்சூழலை பாதுகாக்கிறோம்"},
{en:"The child plays in the park", ta:"குழந்தை பூங்காவில் விளையாடுகிறது"},
{en:"He feeds the birds", ta:"அவன் பறவைகளுக்கு உணவளிக்கிறான்"},
{en:"She washes the clothes", ta:"அவள் உடைகளைத் துவைக்கிறாள்"},
{en:"They collect information", ta:"அவர்கள் தகவல்களை சேகரிக்கிறார்கள்"},
{en:"We support our friends", ta:"நாங்கள் எங்கள் நண்பர்களை ஆதரிக்கிறோம்"}
{en:"He manages the office", ta:"அவன் அலுவலகத்தை நிர்வகிக்கிறான்"},
{en:"She prepares breakfast", ta:"அவள் காலை உணவைத் தயாரிக்கிறாள்"},
{en:"They conduct meetings", ta:"அவர்கள் கூட்டங்களை நடத்துகிறார்கள்"},
{en:"We participate actively", ta:"நாங்கள் சுறுசுறுப்பாக பங்கேற்கிறோம்"},
{en:"The teacher checks the papers", ta:"ஆசிரியர் பதில்தாள்களைச் சரிபார்க்கிறார்"},
{en:"The student asks questions", ta:"மாணவர் கேள்விகளை கேட்கிறார்"},
{en:"The farmer waters the crops", ta:"விவசாயி பயிர்களுக்கு தண்ணீர் ஊற்றுகிறார்"},
{en:"The doctor prescribes medicine", ta:"மருத்துவர் மருந்துகளை எழுதிக்கொடுக்கிறார்"},
{en:"The boy rides a bicycle", ta:"சிறுவன் சைக்கிளை ஓட்டுகிறான்"},
{en:"The girl learns classical dance", ta:"சிறுமி பாரம்பரிய நடனத்தை கற்கிறாள்"},

{en:"He repairs the machine", ta:"அவன் இயந்திரத்தை சரிசெய்கிறான்"},
{en:"She answers the phone", ta:"அவள் தொலைபேசிக்கு பதிலளிக்கிறாள்"},
{en:"They prepare the report", ta:"அவர்கள் அறிக்கையைத் தயாரிக்கிறார்கள்"},
{en:"We visit temples", ta:"நாங்கள் கோவில்களுக்கு செல்கிறோம்"},
{en:"The sun sets in the west", ta:"சூரியன் மேற்கில் அஸ்தமிக்கிறது"},
{en:"The wind blows gently", ta:"காற்று மெதுவாக வீசுகிறது"},
{en:"He attends training programs", ta:"அவன் பயிற்சி நிகழ்ச்சிகளில் கலந்து கொள்கிறான்"},
{en:"She submits the assignment", ta:"அவள் பணியைச் சமர்ப்பிக்கிறாள்"},
{en:"They discuss the topic", ta:"அவர்கள் தலைப்பை விவாதிக்கிறார்கள்"},
{en:"We organize competitions", ta:"நாங்கள் போட்டிகளை ஒழுங்குபடுத்துகிறோம்"},

{en:"The child watches cartoons", ta:"குழந்தை கார்ட்டூன்களைப் பார்க்கிறது"},
{en:"He respects his elders", ta:"அவன் தனது மூத்தவர்களை மதிக்கிறான்"},
{en:"She completes the project", ta:"அவள் திட்டத்தை முடிக்கிறாள்"},
{en:"They follow instructions carefully", ta:"அவர்கள் அறிவுறுத்தல்களை கவனமாகப் பின்பற்றுகிறார்கள்"},
{en:"We attend cultural programs", ta:"நாங்கள் கலாச்சார நிகழ்ச்சிகளில் கலந்து கொள்கிறோம்"},
{en:"The engine produces power", ta:"இயந்திரம் சக்தியை உற்பத்தி செய்கிறது"},
{en:"He practices daily", ta:"அவன் தினமும் பயிற்சி செய்கிறான்"},
{en:"She learns new skills", ta:"அவள் புதிய திறன்களை கற்கிறாள்"},
{en:"They respect their teachers", ta:"அவர்கள் தங்கள் ஆசிரியர்களை மதிக்கிறார்கள்"},
{en:"We contribute to society", ta:"நாங்கள் சமூகத்திற்கு பங்களிக்கிறோம்"},

{en:"The teacher motivates students", ta:"ஆசிரியர் மாணவர்களை ஊக்குவிக்கிறார்"},
{en:"The student completes tasks", ta:"மாணவர் பணிகளை முடிக்கிறார்"},
{en:"The farmer sells vegetables", ta:"விவசாயி காய்கறிகளை விற்பனை செய்கிறார்"},
{en:"The doctor examines patients", ta:"மருத்துவர் நோயாளிகளை பரிசோதிக்கிறார்"},
{en:"The boy studies hard", ta:"சிறுவன் கடினமாகப் படிக்கிறான்"},
{en:"The girl sings melodiously", ta:"சிறுமி இனிமையாகப் பாடுகிறாள்"},
{en:"He works sincerely", ta:"அவன் மனமாரச் செயல்படுகிறான்"},
{en:"She manages her time wisely", ta:"அவள் தனது நேரத்தை புத்திசாலித்தனமாக நிர்வகிக்கிறாள்"},
{en:"They improve their performance", ta:"அவர்கள் தங்கள் செயல்திறனை மேம்படுத்துகிறார்கள்"},
{en:"We achieve our goals", ta:"நாங்கள் எங்கள் இலக்குகளை அடைகிறோம்"}
]
2: [

{en:"He wrote a letter", ta:"அவன் ஒரு கடிதத்தை எழுதினார்"},
{en:"She read a novel", ta:"அவள் ஒரு நாவலைப் படித்தாள்"},
{en:"They played football", ta:"அவர்கள் கால்பந்து விளையாடினர்"},
{en:"We watched the news", ta:"நாங்கள் செய்திகளைப் பார்த்தோம்"},
{en:"The teacher explained the lesson", ta:"ஆசிரியர் பாடத்தை விளக்கினார்"},
{en:"The student answered correctly", ta:"மாணவர் சரியாகப் பதிலளித்தார்"},
{en:"The farmer grew rice", ta:"விவசாயி நெல் வளர்த்தார்"},
{en:"The doctor treated patients", ta:"மருத்துவர் நோயாளிகளை சிகிச்சையளித்தார்"},
{en:"The boy sang a song", ta:"சிறுவன் ஒரு பாடலைப் பாடினான்"},
{en:"The girl drew a picture", ta:"சிறுமி ஒரு படத்தை வரையாள்"},

{en:"He drove a car", ta:"அவன் ஒரு காரை ஓட்டினார்"},
{en:"She cooked dinner", ta:"அவள் இரவு உணவைச் சமைத்தாள்"},
{en:"They cleaned the classroom", ta:"அவர்கள் வகுப்பறையை சுத்தம் செய்தனர்"},
{en:"We learned English grammar", ta:"நாங்கள் ஆங்கில இலக்கணத்தை கற்றோம்"},
{en:"The sun rose in the east", ta:"சூரியன் கிழக்கில் உதித்தது"},
{en:"The moon shone brightly", ta:"நிலா பிரகாசமாக ஒளிர்ந்தது"},
{en:"Birds flew in the sky", ta:"பறவைகள் வானில் பறந்தன"},
{en:"The cat drank milk", ta:"பூனை பாலை குடித்தது"},
{en:"The dog guarded the house", ta:"நாய் வீட்டைக் காத்தது"},
{en:"Students attended classes", ta:"மாணவர்கள் வகுப்புகளில் கலந்து கொண்டனர்"},

{en:"He studied mathematics", ta:"அவன் கணிதத்தைப் படித்தான்"},
{en:"She practiced yoga", ta:"அவள் யோகா பயிற்சி செய்தாள்"},
{en:"They built houses", ta:"அவர்கள் வீடுகளை கட்டினர்"},
{en:"We celebrated festivals", ta:"நாங்கள் திருவிழாக்களை கொண்டாடினோம்"},
{en:"The child smiled happily", ta:"குழந்தை மகிழ்ச்சியாகச் சிரித்தது"},
{en:"He respected his parents", ta:"அவன் தனது பெற்றோர்களை மதித்தான்"},
{en:"She helped the poor", ta:"அவள் ஏழைகளுக்கு உதவினாள்"},
{en:"They planted trees", ta:"அவர்கள் மரங்களை நட்டனர்"},
{en:"We followed the rules", ta:"நாங்கள் விதிகளைப் பின்பற்றினோம்"},
{en:"The engine ran smoothly", ta:"இயந்திரம் சீராக இயங்கியது"},

{en:"He taught science", ta:"அவன் அறிவியலை கற்பித்தான்"},
{en:"She wrote essays", ta:"அவள் கட்டுரைகளை எழுதினாள்"},
{en:"They solved problems", ta:"அவர்கள் பிரச்சினைகளை தீர்த்தனர்"},
{en:"We drank clean water", ta:"நாங்கள் சுத்தமான தண்ணீரைக் குடித்தோம்"},
{en:"The shop opened at nine", ta:"கடை ஒன்பது மணிக்கு திறக்கப்பட்டது"},
{en:"The river flowed rapidly", ta:"நதி வேகமாக ஓடியது"},
{en:"He completed his homework", ta:"அவன் தனது வீட்டுப்பாடத்தை முடித்தான்"},
{en:"She attended the meeting", ta:"அவள் கூட்டத்தில் கலந்து கொண்டாள்"},
{en:"They organized events", ta:"அவர்கள் நிகழ்ச்சிகளை ஒழுங்குபடுத்தினர்"},
{en:"We maintained discipline", ta:"நாங்கள் ஒழுக்கத்தைப் பேணினோம்"},

{en:"The baby cried loudly", ta:"குழந்தை சத்தமாக அழுதது"},
{en:"He bought vegetables", ta:"அவன் காய்கறிகளை வாங்கினார்"},
{en:"She wore a uniform", ta:"அவள் சீருடையை அணிந்தாள்"},
{en:"They traveled by bus", ta:"அவர்கள் பேருந்தில் பயணம் செய்தனர்"},
{en:"We observed silence", ta:"நாங்கள் அமைதியைப் பின்பற்றினோம்"},
{en:"The bell rang loudly", ta:"மணி சத்தமாக ஒலித்தது"},
{en:"He listened carefully", ta:"அவன் கவனமாகக் கேட்டான்"},
{en:"She decorated the hall", ta:"அவள் மண்டபத்தை அலங்கரித்தாள்"},
{en:"They repaired the road", ta:"அவர்கள் சாலையை பழுது பார்த்தனர்"},
{en:"We appreciated good work", ta:"நாங்கள் நல்ல பணியை பாராட்டினோம்"}
{en:"He managed the office", ta:"அவன் அலுவலகத்தை நிர்வகித்தான்"},
{en:"She prepared breakfast", ta:"அவள் காலை உணவைத் தயாரித்தாள்"},
{en:"They conducted meetings", ta:"அவர்கள் கூட்டங்களை நடத்தினர்"},
{en:"We participated actively", ta:"நாங்கள் சுறுசுறுப்பாக பங்கேற்றோம்"},
{en:"The teacher checked the papers", ta:"ஆசிரியர் பதில்தாள்களைச் சரிபார்த்தார்"},
{en:"The student asked questions", ta:"மாணவர் கேள்விகளை கேட்டார்"},
{en:"The farmer watered the crops", ta:"விவசாயி பயிர்களுக்கு தண்ணீர் ஊற்றினார்"},
{en:"The doctor prescribed medicine", ta:"மருத்துவர் மருந்துகளை எழுதிக்கொடுத்தார்"},
{en:"The boy rode a bicycle", ta:"சிறுவன் சைக்கிளை ஓட்டினான்"},
{en:"The girl learned classical dance", ta:"சிறுமி பாரம்பரிய நடனத்தை கற்றாள்"},

{en:"He repaired the machine", ta:"அவன் இயந்திரத்தை சரிசெய்தான்"},
{en:"She answered the phone", ta:"அவள் தொலைபேசிக்கு பதிலளித்தாள்"},
{en:"They prepared the report", ta:"அவர்கள் அறிக்கையைத் தயாரித்தனர்"},
{en:"We visited temples", ta:"நாங்கள் கோவில்களுக்கு சென்றோம்"},
{en:"The sun set in the west", ta:"சூரியன் மேற்கில் அஸ்தமித்தது"},
{en:"The wind blew gently", ta:"காற்று மெதுவாக வீசியது"},
{en:"He attended training programs", ta:"அவன் பயிற்சி நிகழ்ச்சிகளில் கலந்து கொண்டான்"},
{en:"She submitted the assignment", ta:"அவள் பணியைச் சமர்ப்பித்தாள்"},
{en:"They discussed the topic", ta:"அவர்கள் தலைப்பை விவாதித்தனர்"},
{en:"We organized competitions", ta:"நாங்கள் போட்டிகளை ஒழுங்குபடுத்தினோம்"},

{en:"The child watched cartoons", ta:"குழந்தை கார்ட்டூன்களைப் பார்த்தது"},
{en:"He respected his elders", ta:"அவன் தனது மூத்தவர்களை மதித்தான்"},
{en:"She completed the project", ta:"அவள் திட்டத்தை முடித்தாள்"},
{en:"They followed instructions carefully", ta:"அவர்கள் அறிவுறுத்தல்களை கவனமாகப் பின்பற்றினர்"},
{en:"We attended cultural programs", ta:"நாங்கள் கலாச்சார நிகழ்ச்சிகளில் கலந்து கொண்டோம்"},
{en:"The engine produced power", ta:"இயந்திரம் சக்தியை உற்பத்தி செய்தது"},
{en:"He practiced daily", ta:"அவன் தினமும் பயிற்சி செய்தான்"},
{en:"She learned new skills", ta:"அவள் புதிய திறன்களை கற்றாள்"},
{en:"They respected their teachers", ta:"அவர்கள் தங்கள் ஆசிரியர்களை மதித்தனர்"},
{en:"We contributed to society", ta:"நாங்கள் சமூகத்திற்கு பங்களித்தோம்"},

{en:"The teacher motivated students", ta:"ஆசிரியர் மாணவர்களை ஊக்குவித்தார்"},
{en:"The student completed tasks", ta:"மாணவர் பணிகளை முடித்தார்"},
{en:"The farmer sold vegetables", ta:"விவசாயி காய்கறிகளை விற்றார்"},
{en:"The doctor examined patients", ta:"மருத்துவர் நோயாளிகளை பரிசோதித்தார்"},
{en:"The boy studied hard", ta:"சிறுவன் கடினமாகப் படித்தான்"},
{en:"The girl sang melodiously", ta:"சிறுமி இனிமையாகப் பாடினாள்"},
{en:"He worked sincerely", ta:"அவன் மனமாரச் செயல்பட்டான்"},
{en:"She managed her time wisely", ta:"அவள் தனது நேரத்தை புத்திசாலித்தனமாக நிர்வகித்தாள்"},
{en:"They improved their performance", ta:"அவர்கள் தங்கள் செயல்திறனை மேம்படுத்தினர்"},
{en:"We achieved our goals", ta:"நாங்கள் எங்கள் இலக்குகளை அடைந்தோம்"}
]
3: [

{en:"He will write a letter", ta:"அவன் ஒரு கடிதத்தை எழுதுவான்"},
{en:"She will read a novel", ta:"அவள் ஒரு நாவலைப் படிப்பாள்"},
{en:"They will play football", ta:"அவர்கள் கால்பந்து விளையாடுவார்கள்"},
{en:"We will watch the news", ta:"நாங்கள் செய்திகளைப் பார்ப்போம்"},
{en:"The teacher will explain the lesson", ta:"ஆசிரியர் பாடத்தை விளக்குவார்"},
{en:"The student will answer correctly", ta:"மாணவர் சரியாகப் பதிலளிப்பார்"},
{en:"The farmer will grow rice", ta:"விவசாயி நெல் வளர்ப்பார்"},
{en:"The doctor will treat patients", ta:"மருத்துவர் நோயாளிகளை சிகிச்சையளிப்பார்"},
{en:"The boy will sing a song", ta:"சிறுவன் ஒரு பாடலைப் பாடுவான்"},
{en:"The girl will draw a picture", ta:"சிறுமி ஒரு படத்தை வரைவாள்"},

{en:"He will drive a car", ta:"அவன் ஒரு காரை ஓட்டுவான்"},
{en:"She will cook dinner", ta:"அவள் இரவு உணவைச் சமைப்பாள்"},
{en:"They will clean the classroom", ta:"அவர்கள் வகுப்பறையை சுத்தம் செய்வார்கள்"},
{en:"We will learn English grammar", ta:"நாங்கள் ஆங்கில இலக்கணத்தை கற்போம்"},
{en:"The sun will rise tomorrow", ta:"சூரியன் நாளை உதிக்கும்"},
{en:"The moon will shine tonight", ta:"நிலா இன்று இரவில் ஒளிரும்"},
{en:"Birds will fly high", ta:"பறவைகள் உயரமாக பறப்பவை"},
{en:"The cat will drink milk", ta:"பூனை பாலை குடிக்கும்"},
{en:"The dog will guard the house", ta:"நாய் வீட்டைக் காக்கும்"},
{en:"Students will attend classes", ta:"மாணவர்கள் வகுப்புகளில் கலந்து கொள்வார்கள்"},

{en:"He will study mathematics", ta:"அவன் கணிதத்தைப் படிப்பான்"},
{en:"She will practice yoga", ta:"அவள் யோகா பயிற்சி செய்வாள்"},
{en:"They will build houses", ta:"அவர்கள் வீடுகளை கட்டுவார்கள்"},
{en:"We will celebrate the festival", ta:"நாங்கள் திருவிழாவைக் கொண்டாடுவோம்"},
{en:"The child will smile happily", ta:"குழந்தை மகிழ்ச்சியாகச் சிரிக்கும்"},
{en:"He will respect his parents", ta:"அவன் தனது பெற்றோர்களை மதிப்பான்"},
{en:"She will help the poor", ta:"அவள் ஏழைகளுக்கு உதவுவாள்"},
{en:"They will plant trees", ta:"அவர்கள் மரங்களை நடுவார்கள்"},
{en:"We will follow the rules", ta:"நாங்கள் விதிகளைப் பின்பற்றுவோம்"},
{en:"The engine will run smoothly", ta:"இயந்திரம் சீராக இயங்கும்"},

{en:"He will teach science", ta:"அவன் அறிவியலை கற்பிப்பான்"},
{en:"She will write essays", ta:"அவள் கட்டுரைகளை எழுதுவாள்"},
{en:"They will solve problems", ta:"அவர்கள் பிரச்சினைகளை தீர்ப்பார்கள்"},
{en:"We will drink clean water", ta:"நாங்கள் சுத்தமான தண்ணீரைக் குடிப்போம்"},
{en:"The shop will open at nine", ta:"கடை ஒன்பது மணிக்கு திறக்கும்"},
{en:"The river will flow rapidly", ta:"நதி வேகமாக ஓடும்"},
{en:"He will complete his homework", ta:"அவன் தனது வீட்டுப்பாடத்தை முடிப்பான்"},
{en:"She will attend the meeting", ta:"அவள் கூட்டத்தில் கலந்து கொள்வாள்"},
{en:"They will organize events", ta:"அவர்கள் நிகழ்ச்சிகளை ஒழுங்குபடுத்துவார்கள்"},
{en:"We will maintain discipline", ta:"நாங்கள் ஒழுக்கத்தைப் பேணுவோம்"},

{en:"The baby will cry loudly", ta:"குழந்தை சத்தமாக அழும்"},
{en:"He will buy vegetables", ta:"அவன் காய்கறிகளை வாங்குவான்"},
{en:"She will wear a uniform", ta:"அவள் சீருடையை அணிவாள்"},
{en:"They will travel by bus", ta:"அவர்கள் பேருந்தில் பயணம் செய்வார்கள்"},
{en:"We will observe silence", ta:"நாங்கள் அமைதியைப் பின்பற்றுவோம்"},
{en:"The bell will ring soon", ta:"மணி விரைவில் ஒலிக்கும்"},
{en:"He will listen carefully", ta:"அவன் கவனமாகக் கேட்பான்"},
{en:"She will decorate the hall", ta:"அவள் மண்டபத்தை அலங்கரிப்பாள்"},
{en:"They will repair the road", ta:"அவர்கள் சாலையை பழுது பார்ப்பார்கள்"},
{en:"We will appreciate good work", ta:"நாங்கள் நல்ல பணியை பாராட்டுவோம்"}

]
