const sentenceData = [
{english:"He goes to school", tamil:"அவன் பள்ளிக்கு செல்கிறான்"},
{english:"She eats an apple", tamil:"அவள் ஒரு ஆப்பிள் சாப்பிடுகிறாள்"},
{english:"They play cricket", tamil:"அவர்கள் கிரிக்கெட் விளையாடுகிறார்கள்"},
{english:"I read a book", tamil:"நான் ஒரு புத்தகம் படிக்கிறேன்"},
{english:"We watch a movie", tamil:"நாம் ஒரு திரைப்படம் பார்க்கிறோம்"},
{english:"The dog runs fast", tamil:"நாய் வேகமாக ஓடுகிறது"},
{english:"The sun rises in the east", tamil:"சூரியன் கிழக்கில் உதயமாகிறது"},
{english:"She sings a song", tamil:"அவள் ஒரு பாடல் பாடுகிறாள்"},
{english:"He writes a letter", tamil:"அவன் ஒரு கடிதம் எழுதுகிறான்"},
{english:"They drink water", tamil:"அவர்கள் தண்ணீர் குடிக்கிறார்கள்"},
{english:"The boy kicks the ball", tamil:"பையன் பந்தை அடிக்கிறான்"},
{english:"The girl draws a picture", tamil:"பெண் ஒரு படம் வரைகிறாள்"},
{english:"We clean the room", tamil:"நாம் அறையை சுத்தம் செய்கிறோம்"},
{english:"She opens the door", tamil:"அவள் கதவை திறக்கிறாள்"},
{english:"He closes the window", tamil:"அவன் ஜன்னலை மூடுகிறான்"},
{english:"They build a house", tamil:"அவர்கள் ஒரு வீடு கட்டுகிறார்கள்"},
{english:"I ride a bicycle", tamil:"நான் மிதிவண்டி ஓட்டுகிறேன்"},
{english:"We plant a tree", tamil:"நாம் ஒரு மரம் நடுகிறோம்"},
{english:"She washes her hands", tamil:"அவள் கைகளை கழுவுகிறாள்"},
{english:"He feeds the cat", tamil:"அவன் பூனைக்கு உணவு தருகிறான்"},
{english:"They write exams", tamil:"அவர்கள் தேர்வு எழுதுகிறார்கள்"},
{english:"The bird flies high", tamil:"பறவை உயரமாக பறக்கிறது"},
{english:"She studies English", tamil:"அவள் ஆங்கிலம் படிக்கிறாள்"},
{english:"He buys a pen", tamil:"அவன் ஒரு பேனா வாங்குகிறான்"},
{english:"We cook food", tamil:"நாம் உணவு சமைக்கிறோம்"},
{english:"They visit the temple", tamil:"அவர்கள் கோவிலுக்கு செல்கிறார்கள்"},
{english:"The baby sleeps well", tamil:"குழந்தை நன்றாக தூங்குகிறது"},
{english:"She helps her mother", tamil:"அவள் தனது தாய்க்கு உதவுகிறாள்"},
{english:"He drives a car", tamil:"அவன் கார் ஓட்டுகிறான்"},
{english:"We learn new words", tamil:"நாம் புதிய சொற்களை கற்கிறோம்"}
];
